version: '3.7'

networks:
  project-network:
    driver: bridge

services:
  nginx:
    env_file:
      - ../.env.dev
      - ../.env.dev.local

  php:
    ports:
      - "2222:22"   # ssh connection with container
    env_file:
      - ../.env.dev
      - ../.env.dev.local
    environment:
      - DEBUG_EXTENSION=xdebug
      - XDEBUG_MODE=develop,debug
      - XDEBUG_CONFIG=PHPSTORM
      - PHP_IDE_CONFIG=serverName=nginx

  db:
    env_file:
      - ../.env.dev
      - ../.env.dev.local
